### PR TITLE
chore: bump "msw" to 0.28.0

### PR DESCRIPTION
**Pull request by kettanaito**
**What**:

- The `msw` dependency is bumped from `0.27.0` to `0.28.0` ([release notes](https://github.com/mswjs/msw/releases/tag/v0.28.0)).
- The `mockServiceWorker.js` file is re-generated in the React Fundamentals example project.

**Why**:

One of the students of the workshop has reported the following exception caused by MSW:

```
[MSW] Failed to mock a "GET" request to "...": TypeError: Cannot read property 'id' of undefined.
```

This is related to an issue that has been fixed in MSW some time ago.

**How**:

```bash
$ npm i msw@latest
$ npx msw init example/react-fundamentals/public
```

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

### CODE REVIEW

**Comment by kettanaito** [comment]
I believe there's also another repository that relies on `msw`. Could you please point me to it so I update the dependency there as well? Thanks.

**Review by kentcdodds — APPROVED** [review]
Thanks!

All the repos on https://github.com/topics/epicreact-dev will need to update their version of this package when it's released. I can manage that later.

**Comment by kentcdodds** [comment]
@All-contributors please add @kettanaito for code

**Comment by kettanaito** [comment]
Thank you,@kentcdodds 🎉

**Pull request merged**
